name: CI/CD for node application
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24.0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx jest --ci --runInBand
        